### PR TITLE
doc assets

### PR DESCRIPTION
**Pull request by BabylonJSGuide**
Created folder for assets that will be used in example PGs in new docs

### CODE REVIEW

**Comment by RaananW** [comment]
Hi John, you can put each assets in its corresponding directory (glb in meshes, for example). We want the assets repository structure to be as simple as possible

**Comment by BabylonJSGuide** [comment]
> 
> 
> Hi John, you can put each assets in its corresponding directory (glb in meshes, for example). We want the assets repository structure to be as simple as possible

No problem, new commit to do just that.

**Comment by RaananW** [comment]
Is this ready to be merged?

**Comment by BabylonJSGuide** [comment]
Ready

**Pull request merged**
