### PR TITLE
house images

### PR DESCRIPTION
**Pull request by Mekaboo**

### CODE REVIEW

**Comment by sebavan** [comment]
@Mekaboo did you draw the textures ? and if not could you point us at the source so that we could validate the license compatibility ?

**Comment by Mekaboo** [comment]
@sebavan I didnt do the textures but here are the links to the sites:

https://www.freepik.com/free-vector/store-window-shop-building-glass-facade-luxury-house-exterior-grey-stone_13924260.htm#&position=15

https://www.freepik.com/free-vector/house-facade-with-red-brick-wall-window-door_17740248.htm#&position=4

I just noticed it says free but with attribution...that will make a difference

**Comment by sebavan** [comment]
I d say it would be an issue, in this case, you should store it on your own github account, no reason to place it here if not for the doc or sharing with the community what you built :-)

@PatrickRyanMS could help confirm

**Review by sebavan — CHANGES_REQUESTED** [review]
Placing in this mode to prevent accidental merge.

**Comment by PatrickRyanMS** [comment]
We can't put these image on our asset server from the standpoint of the IP terms of use:

> Except as expressly authorized under these Terms, the reproduction or distribution, as well as transformation, producing any derivative works of any kind, public communication, making available, extraction, reuse or any other use of the Website, the Services, the Freepik Content or any of its parts, is strictly forbidden.
> 
> The Third Party Content and the Sponsored Content are protected by intellectual property rights, as appropriate, and belong to their owners. Although the Services can locate and provide access to these contents, its download and use is subject to the conditions set by the relevant third party. The Company is not the owner and cannot grant any license or authorization in relation to Third Party Content or Sponsored Content. The User must obtain authorizations that are, in each case, required to use any Third Party Content or any Sponsored Content.

The license says that it is free for use in personal or commercial applications, but does not stipulate distribution, which is what storing it on our asset server is doing, separating the asset from the third party owner's control over distribution when they uploaded it to Free Vector as the license and protections offered by Free Vector have been sidestepped here. The IP terms of use also state that we would need to go back to the original owner to get permission for distribution. 

This is why we don't merge any content that we can't draw a straight path to creation (i.e. the person uploading the file actually created it). It may seem overly cautious, but it's very easy to separate content from the original user's intent (i.e. it gets moved to a site that does not offer the same license protections for the creator) and end up with a legal mess.

**Pull request closed without merging**
